### PR TITLE
fix: update middy types to be aligned with 7.1.2 update

### LINKED ISSUE #5102: Maintenance: Fix type compatibility with Middy 7.1.3+
## Summary

The `injectLambdaContext` middleware from `@aws-lambda-powertools/logger/middleware` has a type incompatibility with Middy versions 7.1.3 and later. TypeScript compilation fails with `TS2322` when assigning the middleware to `Array<middy.MiddlewareObj>` under strict type checking.

The root cause is that Middy's `Request.error` type changed from `Error | null` to `Error | null | undefined`, breaking compatibility with Powertools' `MiddlewareLikeObj` type definition.

**Related Issue**: https://github.com/middyjs/middy/issues/1599

## Why is this needed?

Users upgrading to Middy 7.1.3+ experience TypeScript compilation errors when using `injectLambdaContext` middleware with strict type checking enabled. This blocks adoption of newer Middy versions and creates friction for users maintaining type-safe Lambda functions.

The error manifests as:
```
error TS2322: Type 'MiddlewareLikeObj' is not assignable to type 'MiddlewareObj<unknown, any, Error, Context, {}>.
  Types of property 'error' are incompatible.
    Type 'Error | null | undefined' is not assignable to type 'Error | null'.
      Type 'undefined' is not assignable to type 'Error | null'.
```

## Which area does this relate to?

- Logger

## Solution

Update the `MiddlewareLikeObj` type definition in the Logger middleware to align with Middy's updated `Request.error` type signature. The `error` property should accept `Error | null | undefined` instead of `Error | null`.

This may require updating type definitions in:
- `@aws-lambda-powertools/logger/middleware`
- Any shared middleware type definitions used across Powertools utilities

## Acknowledgment

- [x] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.aws.amazon.com/powertools/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

---

**Future readers**: Please react with 👍 and your use case to help us understand customer demand.

### PR DESCRIPTION
**Pull request by willfarrell**
## Summary
Type improvements in @middy/core 7.1.2 caused a type miss-match with powertools.

### Changes

allow `undefined` in response / error

Closes https://github.com/middyjs/middy/issues/1599
Fixes #5102
---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by sdangol** [comment]
Hi @willfarrell, could you create an issue for this in this repo and link it to the PR.

File: packages/commons/src/types/middy.ts [hunk 1]
```diff
@@ -60,8 +60,8 @@ type MiddlewareLikeObj<
 type MiddyLikeRequest = {
   event: unknown;
   context: Context;
-  response: unknown;
-  error: Error | null;
+  response: unknown | undefined;
```
Comment (dreamorosi) [inline packages/commons/src/types/middy.ts]: Please let's address this SonarCloud warning

**Comment by dreamorosi** [comment]
> Hi @willfarrell, could you create an issue for this in this repo and link it to the PR.

I got my agent to copy the Middy.js issue and incorporate it into an issue for this repo - thanks for the bias for action of creating a PR here - only one small comment picked up from the SAST.

File: packages/commons/src/types/middy.ts (hunk 1 above)
Comment (willfarrell) [reply packages/commons/src/types/middy.ts]: removed and told my agent to keep this in mind for next time.

**Comment by willfarrell** [comment]
@tstephen-nhs, can you talk a look at this and confirm if it resolves the root issue

**Comment by svozza** [comment]
Soemthing weird going on here, I can't seem to update the branch through GitHub. Could rebase against main and push?

**Comment by willfarrell** [comment]
Likely a GItHub issue, seems to be resolved. I just clicked the button.

**Comment by svozza** [comment]
Apologies @willfarrell, we did a release yesterday and it looks like that update thing happened again. Could you update the branch and I'll merge it straight after.

**Comment by svozza** [comment]
All merged, thank you @willfarrell!
