### PR TITLE
docs(validation): api docs & minor fixes

### LINKED ISSUE #3712: Docs: add API Docs & README for Validation utility
### What were you searching in the docs?

We have recently completed the implementation for the upcoming Validation utility, but haven't written any API docs nor README yet.

### Is this related to an existing documentation section?

_No response_

### How can we improve?

We should write API docs in each public method/function/type/property, so that customers can have an idea of how to use the utility.

The actual utility docs will be reviewed in a separate issue.

### Got a suggestion in mind?

_No response_

### Acknowledgment

- [x] I understand the final update might be different from my proposed suggestion, or refused.

### PR DESCRIPTION
**Pull request by dreamorosi**
### Changes

> Please provide a summary of what's being changed

This PR adds docstrings to all the types/functions/parameters/errors for the upcoming Validation utility and enables Typedoc for the package.

While documenting the code I noticed a few inconsistencies or redundant code paths, which are refactored in this PR along with their respective tests. I also added the build command and removed the `private` marker from the `package.json` file, since we're gonna start publishing in the next release.

> Please add the issue number below, if no issue is present the PR might get blocked and not be reviewed

**Issue number:** closes #3712

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

File: packages/validation/src/types.ts [hunk 1]
```diff
@@ -2,35 +2,79 @@ import type {
...
+   */
   envelope?: string;
+  /**
+   * Optional formats for validation.
+   */
   formats?: Record<
     string,
-    | string
+    Format
+    /* | string
```
Comment (am29d) [inline packages/validation/src/types.ts]: huh? what's that?

**Review by am29d — COMMENTED** [review]
Looks good, just need to clarify accidental comment.

File: packages/validation/src/types.ts (hunk 1 above)
Comment (dreamorosi) [reply packages/validation/src/types.ts]: removed it, it was a leftover from a previous iteration. The final type is `Format`.

**Review by am29d — APPROVED** [review]
