### PR TITLE
feat(parser): fix DynamoDBStreamChangeRecordSchema.dynamodb type 

### LINKED ISSUE #4797: Bug: Inferred type for `DynamoDBStreamRecord` (schema) is incorrect
### Expected Behavior

The type inferred for `DynamoDBStreamRecord` (schema) should include e.g. `SequenceNumber`.

https://github.com/aws-powertools/powertools-lambda-typescript/blob/bccd0b178aa971af8fce755001178beea1316d4b/packages/parser/src/schemas/dynamodb.ts#L12

### Current Behavior

The inferred type seems to be the lowest common denominator of:

https://github.com/aws-powertools/powertools-lambda-typescript/blob/bccd0b178aa971af8fce755001178beea1316d4b/packages/parser/src/schemas/dynamodb.ts#L31-L32

https://github.com/aws-powertools/powertools-lambda-typescript/blob/bccd0b178aa971af8fce755001178beea1316d4b/packages/parser/src/schemas/dynamodb.ts#L22-L27

### Code snippet

```typescript
import {
  DynamoDBStreamRecord as DynamoDBStreamRecordSchema,
} from '@aws-lambda-powertools/parser/schemas/dynamodb';

type DynamoDBStreamRecord = z.infer<typeof DynamoDBStreamRecordSchema>;
```

### Steps to Reproduce

1. Write the above code snippet.
2. Hover over the `DynamoDBStreamRecord` type to see it does not include e.g. `dynamodb.SequenceNumber`.

### Possible Solution

Define the `dynamodb` field as a union e.g.

```typescript
// Make the function generic so we can force particular return types.
const unmarshallDynamoDBTransform = <T extends z.infer<typeof DynamoDBStreamChangeRecordBase> | z.infer<typeof DynamoDBStreamToKinesisChangeRecord>>(
  object: T,
  ctx: z.RefinementCtx
): T => { ... }

// Specialise `DynamoDBStreamChangeRecord` to the full / base type.
const DynamoDBStreamChangeRecord = DynamoDBStreamChangeRecordBase.transform(
  unmarshallDynamoDBTransform<z.infer<typeof DynamoDBStreamChangeRecordBase>>
);

// Add a further type to accommodate the "ToKinesis" version.
const DynamoDBStreamToKinesisChangeRecord = DynamoDBStreamChangeRecordBase.transform(
  unmarshallDynamoDBTransform<z.infer<typeof DynamoDBStreamToKinesisChangeRecord>>
);

// Define `dynamodb field as a union.
const DynamoDBStreamRecord = z.object({
  ...,
  dynamodb: z.union([DynamoDBStreamChangeRecord, DynamoDBStreamToKinesisChangeRecord]),
  ...,
});
```

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

22.x

### Packaging format used

npm

### Execution logs

```Shell

```

### PR DESCRIPTION
**Pull request by benthorner**
### Changes

> Please provide a summary of what's being changed

This fixes a DynamoDB Stream record Zod schema typing issue.

Before:

```typescript
// z.infer<typeof DynamoDBStreamChangeRecord[Schema]>
dynamodb: {
    Keys: Record<string, Record<string, any>>;
    SizeBytes: number;
    ApproximateCreationDateTime?: number | undefined;
    NewImage?: Record<string, any> | undefined;
    OldImage?: Record<string, any> | undefined;
};
```

After:

```typescript
dynamodb: {
    Keys: Record<string, Record<string, any>>;
    SequenceNumber: string;
    SizeBytes: number;
    StreamViewType: "NEW_IMAGE" | "OLD_IMAGE" | "NEW_AND_OLD_IMAGES" | "KEYS_ONLY";
    ApproximateCreationDateTime?: number | undefined;
    NewImage?: Record<string, any> | undefined;
    OldImage?: Record<string, any> | undefined;
} | {
    Keys: Record<string, Record<string, any>>;
    SizeBytes: number;
    ApproximateCreationDateTime?: number | undefined;
    NewImage?: Record<...> | undefined;
    OldImage?: Record<...> | undefined;
};
```

The "before" type is preserved for the Kinesis-only version of the 
schema. As part of this change, we internally suffix `Schema` for 
all properties in `schemas/dynamodb.ts`, which unblocks naming 
some types to support the main fix - see the first commit.

> Please add the issue number below, if no issue is present the PR might get blocked and not be reviewed

**Issue number:** closes #4797

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: packages/parser/src/schemas/dynamodb.ts [hunk 1]
```diff
@@ -19,18 +19,28 @@ const DynamoDBStreamChangeRecordBaseSchema = z.object({
...
+
+const unmarshallDynamoDBTransform = <
+  T extends
+    | DynamoDBStreamChangeRecordBase
+    | DynamoDBStreamToKinesisChangeRecord,
+>(
+  object: T,
   ctx: z.RefinementCtx
-) => {
+): T => {
```
Comment (benthorner) [inline packages/parser/src/schemas/dynamodb.ts:43]: Note: specifying the return type is the crucial part of the fix.

The return type has to be generic: if we specified the concrete union we had previously, the type inferred for the Kinesis-only version of the schema* would then be wrong.

\*`DynamoDBStreamToKinesisRecordSchema`.

File: packages/parser/src/schemas/dynamodb.ts [hunk 2]
```diff
@@ -19,18 +19,28 @@ const DynamoDBStreamChangeRecordBaseSchema = z.object({
   ]),
 });
 
+type DynamoDBStreamChangeRecordBase = z.infer<
```
Comment (benthorner) [inline packages/parser/src/schemas/dynamodb.ts:22]: Note: add some internal types to simplify the changes below.

We could move/export these in `types/schemas.ts` in future, but they're relatively granular so keeping them internal for now gives more flexibility.

Comment (svozza) [reply packages/parser/src/schemas/dynamodb.ts:22]: Agreed

**Comment by svozza** [comment]
Nice ork @benthorner! LGTM.

**Comment by benthorner** [comment]
Thanks for taking a look @svozza! I notice the CI seems to be a bit stuck - anything I can help with?

**Comment by svozza** [comment]
Looks like @sdangol got in before me! All sorted @benthorner, thanks again!
