### PR TITLE
fix(logger): merged temp keys with same keys when appending to the logger 

### LINKED ISSUE #4838: Bug: Temp keys no longer being merged when appended to logger
### Expected Behavior

Say we have an instance of `logger` and we've used `appendKeys()` to add an object `obj` to it.

In `2.28.1`, if we then append `obj` to `logger` again, the existing `obj` is merged with the one being added. For example:

```js
logger.appendKeys({ obj: { key1: 'value' } })
logger.appendKeys({ obj: { key2: 'value' } })
logger.critical('')

// -> { ... "obj":{"key1":"value","key2":"value"}}
```

### Current Behavior

In `2.29.0`, the existing `obj` is replaced by the one being added. For example:

```js
logger.appendKeys({ obj: { key1: 'value' } })
logger.appendKeys({ obj: { key2: 'value' } })
logger.critical('')

// -> { ... "obj":{"key2":"value"}}
```

Note that this does _not_ happen with persistent keys in either `2.28.1` or `2.29.0`:

```js
logger.appendPersistentKeys({ obj: { key1: 'value' } })
logger.appendPersistentKeys({ obj: { key2: 'value' } })
logger.critical('')

// -> { ... "obj":{"key1":"value","key2":"value"}}
```

### Code snippet

```js
import { Logger } from '@aws-lambda-powertools/logger'
const logger = new Logger()

logger.appendKeys({ obj: { key1: 'value' } })
logger.appendKeys({ obj: { key2: 'value' } })
logger.critical('')
```

### Steps to Reproduce

See above.

### Possible Solution

_No response_

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

22.x

### Packaging format used

Lambda Layers

### Execution logs

```Shell

```

### PR DESCRIPTION
**Pull request by sdangol**
## Summary

This PR fixes the issue with the temporary keys not being merged when appending to the Logger. When we try to append a temporary key with an object value when there's a key with the same name, it was getting overridden instead of merging. The keys would get merged previously before [version 2.29.0](https://github.com/aws-powertools/powertools-lambda-typescript/releases/tag/v2.29.0) was released. There were some changes in the logic which caused this change in behavior.

### Changes

> Please provide a summary of what's being changed

- Merged the temporary keys instead of overriding them
- Added tests to verify the behavior

> Please add the issue number below, if no issue is present the PR might get blocked and not be reviewed

**Issue number:** closes #4838 

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

File: packages/logger/src/LogAttributesStore.ts [hunk 1]
```diff
@@ -1,5 +1,6 @@
 import '@aws/lambda-invoke-store';
 import { shouldUseInvokeStore } from '@aws-lambda-powertools/commons/utils/env';
+import merge from 'lodash.merge';
```
Comment (svozza) [inline packages/logger/src/LogAttributesStore.ts:3]: Btw, not for this PR but I would be in favour of us writing our own deep merge utility function in the commons package so we could remove this dependency.

Comment (sdangol) [reply packages/logger/src/LogAttributesStore.ts:3]: Yeah, makes sense. Will create an issue to track that
