### PR TITLE
fix(event-handler): default error handler returns a web Response correctly

### LINKED ISSUE #5013: Bug: Event Handler default error handling does not handle a Response gracefully
### Expected Behavior

Looking at [HttpError.toJSON()](https://github.com/aws-powertools/powertools-lambda-typescript/blob/78091aaa6c27447d6404cafa3e3bf410b8d73ec9/packages/event-handler/src/http/errors.ts#L38) it can technically return a [Response](https://github.com/aws-powertools/powertools-lambda-typescript/blob/78091aaa6c27447d6404cafa3e3bf410b8d73ec9/packages/event-handler/src/types/http.ts#L88) object.  In which case, I would expect that response object to be returned (which may contain header values, etc.).

I 'm aware a custom error handler could be registered, however I feel if we're working with the first party `HttpError` a custom handler _shouldn't_ be required. 

### Current Behavior

The [default error handler](https://github.com/aws-powertools/powertools-lambda-typescript/blob/78091aaa6c27447d6404cafa3e3bf410b8d73ec9/packages/event-handler/src/http/Router.ts#L492) creates and return a new `Response` .

### Code snippet

Extend the `HttpError` and to include some `Header` values and return a `Response` object.

```typescript
import {
	HttpError,
	HttpStatusCodes,
} from "@aws-lambda-powertools/event-handler/http";
import type { HandlerResponse } from "@aws-lambda-powertools/event-handler/types";

export class AuthenticationRequiredError extends HttpError {
	readonly statusCode: 307 = HttpStatusCodes.TEMPORARY_REDIRECT;
	readonly errorType = "login_required";

	readonly headers: Headers;

	constructor(
		redirectTo: URL,
		message?: string,
		options?: ErrorOptions,
		details?: Record<string, unknown>,
	) {
		super(message || "Failed to grant access", options, details);

		this.headers = new Headers([["Location", redirectTo.toString()]]);
	}

	toJSON(): HandlerResponse {
		return Response.json(
			{
				statusCode: this.statusCode,
				error: this.errorType,
				message: this.message,
				...(this.details && {
					details: this.details,
				}),
			},
			{
				status: this.statusCode,
				headers: this.headers,
			},
		);
	}
}
```

### Steps to Reproduce

Simply throw this extended `AuthenticationRequiredError` within the route handler.

### Possible Solution

The fact that [HttpError.toJson()](https://github.com/aws-powertools/powertools-lambda-typescript/blob/78091aaa6c27447d6404cafa3e3bf410b8d73ec9/packages/event-handler/src/http/errors.ts#L38) can return a Response object seems a little strange.  However, a simple instance check here could determine if we already have a `Response` or need to create a new one.

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

24.x

### Packaging format used

npm

### Execution logs

```Shell

```

### PR DESCRIPTION
**Pull request by nateiler**
## Summary
The default router error handling was not handling a `Response` object correctly when returned from the `toJSON` method.

### Changes
The base `HttpError` now has a correct `toJSON` response type and an added `toWebResponse` method which is responsible for constructing a web `Response` for the default error handler.  Errors that extend the `HttpError` can easily modify the `Response` (ex: adding additional headers, etc).

**Issue number:** closes #5013

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

File: packages/event-handler/src/http/errors.ts [hunk 1]
```diff
@@ -45,6 +45,13 @@ abstract class HttpError extends Error {
       }),
     };
   }
+
+  toWebResponse(): Response {
+    return new Response(JSON.stringify(this.toJSON()), {
```
Comment (svozza) [inline packages/event-handler/src/http/errors.ts]: Could we use the `Response.json` static method here??

File: packages/event-handler/tests/unit/http/errors.test.ts [hunk 2]
```diff
@@ -174,6 +178,111 @@ describe('HTTP Error Classes', () => {
...
+      statusCode,
+      message,
+    }) => {
+      const error = new ErrorClass(message);
+      const response = error.toWebResponse();
+
+      expect(response.status).toEqual(statusCode);
+      expect(response.headers.get('Content-Type')).toEqual('application/json');
+
+      expect(await response.json()).toEqual({
```
Comment (svozza) [inline packages/event-handler/tests/unit/http/errors.test.ts]: Let's use the `resolves` assertions for these async verifications: https://vitest.dev/api/expect.html#resolves.

File: packages/event-handler/src/http/errors.ts (hunk 1 above)
Comment (nateiler) [reply packages/event-handler/src/http/errors.ts]: Good catch!  Fixed

File: packages/event-handler/tests/unit/http/errors.test.ts (hunk 2 above)
Comment (nateiler) [reply packages/event-handler/tests/unit/http/errors.test.ts]: Learn something new everyday!  Fixed

**Comment by svozza** [comment]
Nice work @nateiler, merging now!
