### PR TITLE
fix(logger): infinite loop on log buffer when item size is max bytes

### LINKED ISSUE #4737: Bug: Log buffer would run an infinite loop when the size of the log is exactly the same as the maxBytes size specified.
### Expected Behavior

It should not keep attempting to remove from the log buffer (if it's currently empty).

### Current Behavior

It keeps attempting to remove from the buffer even if the buffer is empty.

There are checks to make sure that the item size is less than or equal to the maximum size however, subsequent checks check that the `item size + buffer size` is less than the maximum size.

So in an execution where:
`maxBytes` is `20000`
`item size`  is `20000`
`buffer size` is `0`

there would be an infinite loop because while it attempts to remove from the map.

if item size was greater than `item size`, it would have thrown an error instead.

### Code snippet

link to code:

https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/packages/logger/src/logBuffer.ts#L135

### Steps to Reproduce

1. Enable buffered logs
2. get log data that would be exactly same as the maxBytes specified

### Possible Solution

Either check that the item size is definitely less than max bytes (not less than or equal)
or only attempt to remove from the `buffer` if there is something in the buffer

```javascript
while (buffer.currentBytesSize + item.byteSize >= this.#maxBytesSize && buffer.currentBytesSize) {
```

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

22.x

### Packaging format used

npm

### Execution logs

```Shell

```

### PR DESCRIPTION
**Pull request by fidelisojeah**
### Changes

> Please provide a summary of what's being changed

This PR fixes a bug where an infinite loop occurs when a new buffered log's byte size is equal to the maxBytes size (`logBufferOptions.maxBytes`) specified while log buffering is enabled (`logBufferOptions.enabled = true`).

See issue for more details.

> Please add the issue number below, if no issue is present the PR might get blocked and not be reviewed

**Issue number:** closes #4737

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by dreamorosi** [comment]
Thank you for the PR, we'll review it soon.

File: packages/logger/src/logBuffer.ts [hunk 1]
```diff
@@ -132,7 +136,10 @@ export class CircularMap<V> extends Map<string, SizedSet<V>> {
     buffer: SizedSet<V>,
     item: SizedItem<V>
   ) {
-    while (buffer.currentBytesSize + item.byteSize >= this.#maxBytesSize) {
+    while (
+      buffer.size &&
```
Comment (fidelisojeah) [inline packages/logger/src/logBuffer.ts]: choosing to use the `set.size` here rather than checking against `currentBytesSize`

**Review by dreamorosi — COMMENTED** [review]
Set @svozza as reviewer

File: packages/logger/src/logBuffer.ts [hunk 2]
```diff
@@ -110,8 +110,12 @@ export class CircularMap<V> extends Map<string, SizedSet<V>> {
 
     const buffer = this.get(key) || new SizedSet<V>();
 
-    if (buffer.currentBytesSize + item.byteSize >= this.#maxBytesSize) {
+    if (
+      buffer.currentBytesSize &&
```
Comment (svozza) [inline packages/logger/src/logBuffer.ts]: Can we be explicit here and check exactly rather than relying on type coercion: `!== 0`.

File: packages/logger/src/logBuffer.ts (hunk 1 above)
Comment (svozza) [reply packages/logger/src/logBuffer.ts]: Same comment regarding type coercion.

**Comment by svozza** [comment]
Nice work @fidelisojeah! I only had two very minor comments.

File: packages/logger/src/logBuffer.ts (hunk 2 above)
Comment (fidelisojeah) [reply packages/logger/src/logBuffer.ts]: updated

File: packages/logger/src/logBuffer.ts (hunk 1 above)
Comment (fidelisojeah) [reply packages/logger/src/logBuffer.ts]: Updated

Comment (svozza) [reply packages/logger/src/logBuffer.ts]: Great, everything looks good to me.

**Comment by svozza** [comment]
Great stuff @fidelisojeah , merging now!
