### PR TITLE
test: add e2e tests for batch processing

### LINKED ISSUE #4489: Maintenance: add e2e tests for Batch Processing
### Summary

Following the `v2.26.0` release we introduced a regression that couldn't be detected in unit tests and existing e2e tests. 

Because of this, we should add isolated and dedicated test cases for the Batch Processing utility.

### Why is this needed?

So that we can increase the confidence that new code in this utility stays backwards compatible and with less chances of regressions.

### Which area does this relate to?

Other

### Solution

_No response_

### Acknowledgment

- [x] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

### PR DESCRIPTION
**Pull request by dreamorosi**
### Changes

> Please provide a summary of what's being changed

This PR adds an integration test case for the Batch Processing utility, which was not previously covered. The test purposefully includes only one test case with standard SQS queue since the main goal of the test is to verify that the utility works in Lambda together with Parser, rather than covering the entire spectrum of features of the utility, which rely on similar implementations anyway.

To create this test I had to implement a new utility function that tails CloudWatch logs since this is also the first test that we add that can't be observed by querying logs or by collecting the response of a specific function invocation. This is due to the fact that we only publish messages to a SQS queue and we don't control how many or when the function invocations will happen.

This new testing utility lives under the packages/testing package and handles the tailing of a CloudWatch Log Group, collects the logs, and stops tailing after a given idle time.

> Please add the issue number below, if no issue is present the PR might get blocked and not be reviewed

**Issue number:** closes #4489

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by dreamorosi** [comment]
Integration [tests - including the new ones - are green](https://github.com/aws-powertools/powertools-lambda-typescript/actions/runs/21472169288).

File: packages/testing/src/LogTailer.ts [hunk 1]
```diff
@@ -0,0 +1,349 @@
...
+    };
+
+    refreshIdleTimer();
+
+    try {
+      for await (const event of this.#response.responseStream || []) {
+        if (aborted) break;
+
+        const hadLogData = this.#collectSessionResults(
+          event.sessionUpdate?.sessionResults,
```
Comment (svozza) [inline packages/testing/src/LogTailer.ts]: If we have a fallback value here we can remove `undefined` from the type signature of the `sessionResults` param in `collectSessionResults`:

```ts
event.sessionUpdate?.sessionResults ?? [];
```

File: packages/testing/src/LogTailer.ts [hunk 2]
```diff
@@ -0,0 +1,349 @@
...
+          requestLogs
```
Comment (svozza) [inline packages/testing/src/LogTailer.ts]: Rather than passing an empty `map` in here and then mutating it, could the map  creation and population be in `collectSessionResults` and have this function return the map instead? Then the check here just becomes a check to see if the map is empty or not. It's confusing to me to have a function called `collectX` that returns a boolean rather than a collection.

File: packages/testing/src/LogTailer.ts [hunk 3]
```diff
@@ -0,0 +1,349 @@
...
+    if (!sessionResults?.length) return false;
+
+    for (const logEvent of sessionResults) {
+      const { requestId, logObj } = this.#parseLogEvent(logEvent);
+      if (!requestId || !logObj) continue;
+
+      if (!requestLogs.has(requestId)) {
+        requestLogs.set(requestId, []);
+      }
+      requestLogs.get(requestId)?.push(logObj);
```
Comment (svozza) [inline packages/testing/src/LogTailer.ts]: Do we need this `?`, we've already checked above with `requestLogs.has(requestId)` so we know the array will be here.

File: packages/testing/src/LogTailer.ts [hunk 4]
```diff
@@ -0,0 +1,349 @@
...
+
+        if (this.#shouldAutoStop(requestLogs, cooldownState)) {
+          markAborted();
+          break;
+        }
+      }
+
+      if (idleTimer) clearTimeout(idleTimer);
+
+      for (const logs of requestLogs.values()) {
```
Comment (svozza) [inline packages/testing/src/LogTailer.ts]: Am I following the logic correctly here: the code creates an iterator of arrays from a map, then mutates each of those arrays in place from the original map that was passed in, and then returns that map whose values been mutated? 

To make this a bit easier to follow, could this sorting logic also be moved to `collectSessionResults` so all the mutation is confined to a single a function that just returns a map of sorted logs.

File: packages/testing/src/LogTailer.ts (hunk 3 above)
Comment (dreamorosi) [reply packages/testing/src/LogTailer.ts]: I agree and dislike it, but this is a long standing limitation of TypeScript (see microsoft/TypeScript#13086) that causes it to not be able to "follow" the flow analysis. Removing the `?` would mean either adding a `!` plus a linting suppression, or adding a `ts-ignore`, so I went for `?`.

Comment (svozza) [reply packages/testing/src/LogTailer.ts]: Ah yes, this has caught me before too, `?` is definitely preferable imo.

**Comment by dreamorosi** [comment]
Thanks for the review @svozza - good shouts on the simplification, I think I addressed most/all of them, let me know if this is what you had in mind.

File: packages/testing/src/LogTailer.ts [hunk 5]
```diff
@@ -0,0 +1,354 @@
...
+    try {
+      for await (const event of this.#response.responseStream || []) {
+        if (aborted) break;
+
+        const sessionResults = event.sessionUpdate?.sessionResults ?? [];
+        if (sessionResults.length > 0) {
+          refreshIdleTimer();
+        }
+
+        requestLogs = this.#collectSessionResults(sessionResults, requestLogs);
```
Comment (svozza) [inline packages/testing/src/LogTailer.ts:336]: Do we need to pass this map in now? It will always empty because of the definition on L304. I think `sessionResults` as the only param is sufficient now that the map is constucted from this array.

**Comment by svozza** [comment]
> Thanks for the review @svozza - good shouts on the simplification, I think I addressed most/all of them, let me know if this is what you had in mind.

One tiny comment but other than that LGTM.

File: packages/testing/src/LogTailer.ts (hunk 5 above)
Comment (dreamorosi) [reply packages/testing/src/LogTailer.ts:336]: It's not always empty because we can process multiple log streams in the same tailing session - if we drop it, the next stream will always replace the previous I think.

Comment (svozza) [reply packages/testing/src/LogTailer.ts:336]: Ah I get you!
