### PR TITLE
fix(parser): lambda function url cognitoIdentity and principalOrgId nullable

### LINKED ISSUE #2427: Bug: LambdaFunctionUrlSchema fails with CloudFront Origin Access Control (OAC)
### Expected Behaviour

Using `.use(parser({ schema: LambdaFunctionUrlSchema }))` middleware should work with Lambda Function URLs protected by [the newly launched CloudFront OACs](https://aws.amazon.com/about-aws/whats-new/2024/04/amazon-cloudfront-oac-lambda-function-url-origins/).

### Current Behaviour

The parser throws an error:
```
Failed to parse schema. This error was caused by: [
  
{
    "code": "invalid_type",
    "expected": "string",
    "received": "null",
    "path": [
        "requestContext",
        "authorizer",
        "iam",
        "principalOrgId"
    ],
    "message": "Expected string, received null"
}
,
  
{
    "code": "invalid_type",
    "expected": "object",
    "received": "null",
    "path": [
        "requestContext",
        "authorizer",
        "iam",
        "cognitoIdentity"
    ],
    "message": "Expected object, received null"
}
```

This is because when CloudFront OAC is calling the Lambda Function URL, the [`principalOrgId`](https://github.com/aws-powertools/powertools-lambda-typescript/blob/744fad76bb7bad96799506981a63d3c59f5a93e2/packages/parser/src/schemas/apigwv2.ts#L16) and [`cognitoIdentity`](https://github.com/aws-powertools/powertools-lambda-typescript/blob/744fad76bb7bad96799506981a63d3c59f5a93e2/packages/parser/src/schemas/apigwv2.ts#L19C7-L23) are actual set to `null`:
```js
// some sensitive'ish values replaced with fictional values
"requestContext": {
            "accountId": "123456789012",
            "apiId": "abcd1",
            "authorizer": {
                "iam": {
                    "accessKey": "ASIA123EXAMPLE",
                    "accountId": "123456789012",
                    "callerId": "AROA123EXAMPLE:OriginAccessSession",
/* NOTICE NULL → */ "cognitoIdentity": null, 
/* NOTICE NULL → */ "principalOrgId": null,  
                    "userArn": "arn:aws:sts::123456789012:assumed-role/OriginAccessControlRole/OriginAccessSession",
                    "userId": "AROA123EXAMPLE:OriginAccessSession"
                }
            },
```

### Code snippet

`.use(parser({ schema: LambdaFunctionUrlSchema }))` with Lambda Function URL + CloudFront OAC

### Steps to Reproduce

Creating a full example is a bit too much work for right now, but you can take my minimal Lambda Function URL + CloudFront OAC example from https://github.com/aws/aws-cdk/issues/21771#issuecomment-2073425721 and replace the Lambda function with a TS one using `.use(parser({ schema: LambdaFunctionUrlSchema }))` middleware.

### Possible Solution

- Make `principalOrgId` nullable
- Make `cognitoIdentity` nullable

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

20.x

### Packaging format used

npm

### Execution logs

_No response_

### PR DESCRIPTION
**Pull request by am29d**
## Description of your changes

This PR closes #2427 . I have used `optional` in most of the places where we don't expect to have a value, but this did not cover the `null` value case. 

### Related issues, RFCs

**Issue number:** closes #2427

## Checklist

- [x] [My changes meet the tenets criteria](https://docs.powertools.aws.dev/lambda/typescript/#tenets)
- [x] I have performed a *self-review* of my own code
- [ ] I have *commented* my code where necessary, particularly in areas that should be flagged with a TODO, or hard-to-understand areas
- [ ] I have made corresponding changes to the *documentation*
- [x] My changes generate *no new warnings*
- [ ] I have *added tests* that prove my change is effective and works
- [x] The PR title follows the [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/.github/semantic.yml#L2)

### Breaking change checklist

***Is it a breaking change?:*** NO

- [ ] I have documented the migration process
- [ ] I have added, implemented necessary warnings (if it can live side by side)

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

File: packages/parser/src/schemas/apigwv2.ts [hunk 1]
```diff
@@ -13,14 +13,16 @@ const RequestContextV2Authorizer = z.object({
       accessKey: z.string().optional(),
       accountId: z.string().optional(),
       callerId: z.string().optional(),
-      principalOrgId: z.string().optional(),
+      principalOrgId: z.string().nullable(),
```
Comment (dreamorosi) [inline packages/parser/src/schemas/apigwv2.ts:16]: Are there cases where this field is not there at all? Or will it always be a string or `null`?

File: packages/parser/src/schemas/apigwv2.ts [hunk 2]
```diff
@@ -42,7 +44,7 @@ const RequestContextV2 = z.object({
     .object({
       clientCert: APIGatewayCert.optional(),
     })
-    .optional(),
+    .nullish(),
```
Comment (dreamorosi) [inline packages/parser/src/schemas/apigwv2.ts:47]: Same comment as [here](https://github.com/aws-powertools/powertools-lambda-typescript/pull/2430/files#r1577636663).

File: packages/parser/src/schemas/apigwv2.ts (hunk 1 above)
Comment (am29d) [reply packages/parser/src/schemas/apigwv2.ts:16]: `nullish` is weaker and is imho preferable. 

`z.string().nullable()` is `string | null` while `z.string().nullish()` is  `string | null | undefined` 

I am not sure there are cases where we need the key to be present. Python does similar, which I misunderstood `Optional[str] = None` always set the field to `None` if it's not present.

**Review by dreamorosi — APPROVED** [review]
