### PR TITLE
fix(parser): allow SQS envelopes to handle non-JSON strings

### LINKED ISSUE #3510: Bug: SQS Envelope assumes message body is always a JSON
### Expected Behavior

When working with the `SqsEnvelope` I should be able to extract the message body regardless of whether it's a plain text string or a JSON-stringified one.

### Current Behavior

When the message body is not a JSON-stringified object the envelope throws a runtime error as it's unable to parse it with `JSON.parse()`.

### Code snippet

```ts
import { z } from 'zod';
import { SqsEnvelope } from '@aws-lambda-powertools/parser/envelopes';

export const handler = async (event) => {
  try {
    SqsEnvelope.parse(event, z.string());
  } catch (error) {
    console.error(error);
  }
}
```

### Steps to Reproduce

Send a message like this:

```
aws sqs send-message \           
  --queue-url https://sqs.eu-west-1.amazonaws.com/123456789012/sqs-parser-MyQueue \
  --message-body 'hello'
```

Observe the logs:

```
 ParseError: Failed to parse envelope. This error was caused by:
 Unexpected token 'h', "hello" is not valid JSON.
```

### Possible Solution

We should avoid parsing by default and instead leave it to the caller to decide.

While working on this, we should also check the SQS Schema and the SNS + SQS Envelope, since they share some of the code.

Additionally, we should ensure the schema fails parsing when the `Records` array is empty, as mentioned in #3475.

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

22.x

### Packaging format used

npm

### Execution logs

```Shell

```

### PR DESCRIPTION
**Pull request by dreamorosi**
### Changes

> Please provide a summary of what's being changed

This PR updates the `SqsEnvelope` and `SnsSqsEnvelope` so that they can handle messages other than JSON strings, i.e. plain text strings like `"hello world"`.

The PR is still WIP and I will update the description once it's done.

To complete this PR I also had to refactor the Middy.js middleware unit tests since they were using the SQS envelope I was touching. Because of this I took the opportunity to simplify & standardize them so that they follow the same conventions as the rest of the project.

> Please add the issue number below, if no issue is present the PR might get blocked and not be reviewed

**Issue number:** fixes #3510

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

File: packages/parser/src/envelopes/snssqs.ts [hunk 1]
```diff
@@ -0,0 +1,185 @@
...
+        );
+      } catch (error) {
+        throw new ParseError(
+          `Failed to parse SQS Record at index ${recordIndex}`,
+          {
+            cause: new ZodError(
+              error instanceof ZodError
+                ? (error as ZodError).issues.map((issue) => ({
+                    ...issue,
+                    path: ['Records', recordIndex, 'body', ...issue.path],
```
Comment (am29d) [inline packages/parser/src/envelopes/snssqs.ts:82]: Now that we have `createError` helper, do you think it'd make sense to use it here, and add later to other envelopes? We probably need ot pass the 2nd parameter as input, as it's often different. What do you think?

**Review by am29d — COMMENTED** [review]
Thanks for the PR! Just a minor question on reusing `createError` helper.

File: packages/parser/src/envelopes/snssqs.ts (hunk 1 above)
Comment (dreamorosi) [reply packages/parser/src/envelopes/snssqs.ts:82]: Yea, possibly.

I think let's go through all the envelopes and then we see where we can simplify / extract further. Using this function removes also the `// @ts-expect-error` since it's now properly typed.

I'd rather complete the entire refactor first though, as I don't want to backtrack before getting to the end. Ideally I'd like to make it to the next release with most/all the envelopes bugs fixed - then we can refactor and optimize.

**Review by leandrodamascena — APPROVED** [review]
